### ISSUE TITLE
which tool you use to generate svg file ? 

### ISSUE THREAD

**Issue by yanxinmiao** [geftimov/android-pathview#35]
use the svg file that I generated having a problem :

 com.caverock.androidsvg.SVGParseException: SVG parse error: At line 2, column 51: syntax error
                                                              at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:611)
                                                              at com.caverock.androidsvg.SVG.getFromResource(SVG.java:187)
                                                              at com.caverock.androidsvg.SVG.getFromResource(SVG.java:172)
                                                              at com.eftimoff.androipathview.SvgUtils.load(SvgUtils.java:60)
                                                              at com.eftimoff.androipathview.PathView$1.run(PathView.java:242)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: org.apache.harmony.xml.ExpatParser$ParseException: At line 2, column 51: syntax error
                                                              at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:515)
                                                              at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
                                                              at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
                                                              at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
                                                              at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:599)
                                                              at com.caverock.androidsvg.SVG.getFromResource(SVG.java:187) 
                                                              at com.caverock.androidsvg.SVG.getFromResource(SVG.java:172) 
                                                              at com.eftimoff.androipathview.SvgUtils.load(SvgUtils.java:60) 
                                                              at com.eftimoff.androipathview.PathView$1.run(PathView.java:242) 
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by geftimov** [comment]
My library is using androidsvg to read the paths in the svg. Your problem is in your svg.
